services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-shre}"
    image: cbd-data-preparation
    platform: linux/amd64
    container_name: cbd-data-preparation-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-shre}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-shre}/.config/gcloud
    ports:
      - 8080:8080
    ipc: host
    init: true


