infrastructure:
  project_id: mlops-422011
  zone: asia-south1-c
  network: default
data_parquet_path: gs://cbd_data/data/processed/rebalanced_splits/train.parquet
text_column_name: cleaned_text
tokenizer:
  _target_: cybulde.tokenization.tokenizers.HuggingFaceTokenizer
  pre_tokenizer:
    _target_: tokenizers.pre_tokenizers.Whitespace
  model:
    _target_: tokenizers.models.BPE
    vocab: null
    merges: null
    cache_capacity: 10000
    dropout: null
    unk_token: '[UNK]'
    fuse_unk: false
  trainer:
    _target_: tokenizers.trainers.BpeTrainer
    vocab_size: 30000
    show_progress: true
    min_frequency: 0
    special_tokens:
    - '[UNK]'
    - '[CLS]'
    - '[SEP]'
    - '[PAD]'
    - '[MASK]'
    initial_alphabet: []
  normalizer: null
  decoder: null
  post_processor: null
  unk_token: '[UNK]'
  cls_token: '[CLS]'
  sep_token: '[SEP]'
  pad_token: '[PAD]'
  mask_token: '[MASK]'
docker_image_name: asia-south1-docker.pkg.dev/mlops-422011/cbd/cbd-data-preparation
docker_image_tag: 3d5b02d4-3a75-4244-bc10-d748197b6fee
